name: deploy_to_firebase_hosting

on:
  push:
    branches:
      - 'master'

jobs:
  deploy_to_firebase_hosting:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    env:
      VHOYER_FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.VHOYER_FONTAWESOME_NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Load dependencies versions
        id: versions
        run: |
          echo "node=$(sed -n 's/NODE_VERSION=//p' .env)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@master
        with:
          node-version: ${{ steps.versions.outputs.node }}
          cache: 'npm' # save global npm install cache

      - name: Generate Dependencies Cache
        id: dependencies
        uses: actions/cache@main
        with:
          path: |
            node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.dependencies.outputs.cache-hit != 'true'
        run: npm clean-install

      - name: Build project
        run: |
          npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONEY_CTRL }}'
          channelId: live
          projectId: money-ctrl
